# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# Declare Chrome Driver
driver = webdriver.Chrome("./chromedriver")

# Timeout Set To 10 Seconds
driver.set_page_load_timeout(10)

# Loading message
print("....Navigating to the Geekhive webpage...")

# Open Geekhive Site
driver.get("http://www.geekhive.com/")

# Set Window Size
driver.set_window_size(1400, 1214)

# Click Work Link In Header Nav 
driver.find_element(By.CSS_SELECTOR, ".menu-item:nth-child(4) > .menu-item-link").click()

# Declare Search Field Variable
search = driver.find_element(By.ID, "edit-keywords")

# Search For 'aruba' In Work Search Field
search.send_keys("aruba")

# CLick Search Icon
driver.find_element(By.ID, "edit-submit-case-studies").click()

# Search Work Form: 'shire'
driver.get("https://www.geekhive.com/work?keywords=shire")

WebDriverWait: 50

# Search Work Form: 'coach'
driver.get("https://www.geekhive.com/work?keywords=coach")



############################################ TEST CODE BELOW ############################################
# Erase 'aruba'
#search = driver.find_element(By.ID, "edit-keywords")
#search.send_keys(Keys.CONTROL + "a")
#search.send_keys(Keys.DELETE)

# Search For 'shire' In Work Search Field
#search.send_keys("shire")

# CLick Search Icon
#driver.find_element(By.ID, "edit-submit-case-studies").click()

# Stopped Here
#search.send_keys(Keys.CONTROL + "a")
#search.send_keys(Keys.DELETE)

#search.send_keys("coach")

# CLick Search Icon
#driver.find_element(By.ID, "edit-submit-case-studies").click()
