# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome("./chromedriver")
    self.vars = {}
  
  def teardown_method(self, method):
        self.driver.quit()
  
  def test_advocacy(self):
    self.driver = webdriver.Chrome("./chromedriver")
    
    # Test name: Advocacy
    # Step # | name | target | value
    # 1 | open | /advocacy | 
    self.driver.get("https://www.hematology.org/advocacy")
    # 2 | setWindowSize | 1600x1210 | 
    self.driver.set_window_size(1600, 1210)
    # 3 | click | css=.btn:nth-child(3) > .mb-0 | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3) > .mb-0").click()
    # 4 | click | css=#cardNavigator_a06186b82-1f9b-43f5-ab14-79163fa7e3ef > .slick-next | 
    ## self.driver.find_element(By.CSS_SELECTOR, "#cardNavigator_a06186b82-1f9b-43f5-ab14-79163fa7e3ef > .slick-next").click()
    # 5 | click | css=#cardNavigator_a06186b82-1f9b-43f5-ab14-79163fa7e3ef > .slick-next | 
    
    element = self.driver.find_element_by_link_text("CMSS LETTER")
    # 6 | click | css=.slick-active:nth-child(5) .card-link | 
    
    print(element.is_visible()) 

# Define Class as Advocacy
Advocacy = TestDefaultSuite()

# Run Advocacy
Advocacy.setup_method(Advocacy)

# Run Test Case test_avocacy
Advocacy.test_advocacy()

# Terminate Advocacy
Advocacy.teardown_method(Advocacy)

# Define this as main test suite
if __name__ == "__main__":
      # Run Unit Tests
   unittest.main()