// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class UntitledTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
[TestInitialize()]
public void SetupTest()
{
    var options = new ChromeOptions();
    options.AddArguments("headless");
    driver = new ChromeDriver(options);
    
}
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void untitled() {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | /coach-landing-page | 
    driver.Navigate().GoToUrl("https://authoring.dev.abcga.ghclients.com/coach-landing-page");
    // 2 | setWindowSize | 1060x810 | 
    driver.Manage().Window.Size = new System.Drawing.Size(1060, 810);
    // 3 | click | css=.popover-button > img:nth-child(1) | 
    driver.FindElement(By.CssSelector(".popover-button > img:nth-child(1)")).Click();
    // 4 | click | linkText=Your Accounts | 
    driver.FindElement(By.LinkText("Your Accounts")).Click();
    // 5 | click | css=a > img | 
    driver.FindElement(By.CssSelector("a > img")).Click();
    // 6 | click | id=search-bar | 
    driver.FindElement(By.Id("search-bar")).Click();
    // 7 | type | id=search-bar | Value
    driver.FindElement(By.Id("search-bar")).SendKeys("Value");
    // 8 | sendKeys | id=search-bar | ${KEY_ENTER}
    driver.FindElement(By.Id("search-bar")).SendKeys(Keys.Enter);
  }
}
